<?php

use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('paises')->insert([

            ['iso' => 'AF', 'nombre' => 'Afganistán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AX', 'nombre' => 'Islas Gland', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AL', 'nombre' => 'Albania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'DE', 'nombre' => 'Alemania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AD', 'nombre' => 'Andorra', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AO', 'nombre' => 'Angola', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AI', 'nombre' => 'Anguilla', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AQ', 'nombre' => 'Antártida', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AG', 'nombre' => 'Antigua y Barbuda', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AN', 'nombre' => 'Antillas Holandesas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SA', 'nombre' => 'Arabia Saudí', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'DZ', 'nombre' => 'Argelia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AR', 'nombre' => 'Argentina', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AM', 'nombre' => 'Armenia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AW', 'nombre' => 'Aruba', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AU', 'nombre' => 'Australia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AT', 'nombre' => 'Austria', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AZ', 'nombre' => 'Azerbaiyán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BS', 'nombre' => 'Bahamas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BH', 'nombre' => 'Bahréin', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BD', 'nombre' => 'Bangladesh', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BB', 'nombre' => 'Barbados', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BY', 'nombre' => 'Bielorrusia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BE', 'nombre' => 'Bélgica', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BZ', 'nombre' => 'Belice', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BJ', 'nombre' => 'Benin', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BM', 'nombre' => 'Bermudas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BT', 'nombre' => 'Bhután', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BO', 'nombre' => 'Bolivia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BA', 'nombre' => 'Bosnia y Herzegovina', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BW', 'nombre' => 'Botsuana', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BV', 'nombre' => 'Isla Bouvet', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BR', 'nombre' => 'Brasil', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BN', 'nombre' => 'Brunéi', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BG', 'nombre' => 'Bulgaria', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BF', 'nombre' => 'Burkina Faso', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'BI', 'nombre' => 'Burundi', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CV', 'nombre' => 'Cabo Verde', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KY', 'nombre' => 'Islas Caimán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KH', 'nombre' => 'Camboya', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CM', 'nombre' => 'Camerún', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CA', 'nombre' => 'Canadá', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CF', 'nombre' => 'República Centroafricana', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TD', 'nombre' => 'Chad', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CZ', 'nombre' => 'República Checa', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CL', 'nombre' => 'Chile', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CN', 'nombre' => 'China', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CY', 'nombre' => 'Chipre', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CX', 'nombre' => 'Isla de Navidad', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VA', 'nombre' => 'Ciudad del Vaticano', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CC', 'nombre' => 'Islas Cocos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CO', 'nombre' => 'Colombia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KM', 'nombre' => 'Comoras', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CD', 'nombre' => 'República Democrática del Congo', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CG', 'nombre' => 'Congo', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CK', 'nombre' => 'Islas Cook', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KP', 'nombre' => 'Corea del Norte', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KR', 'nombre' => 'Corea del Sur', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CI', 'nombre' => 'Costa de Marfil', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CR', 'nombre' => 'Costa Rica', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'HR', 'nombre' => 'Croacia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CU', 'nombre' => 'Cuba', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'DK', 'nombre' => 'Dinamarca', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'DM', 'nombre' => 'Dominica', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'EC', 'nombre' => 'Ecuador', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'EG', 'nombre' => 'Egipto', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SV', 'nombre' => 'El Salvador', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AE', 'nombre' => 'Emiratos Árabes Unidos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ER', 'nombre' => 'Eritrea', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SK', 'nombre' => 'Eslovaquia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SI', 'nombre' => 'Eslovenia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ES', 'nombre' => 'España', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'UM', 'nombre' => 'Islas ultramarinas de Estados Unidos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'US', 'nombre' => 'Estados Unidos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'EE', 'nombre' => 'Estonia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ET', 'nombre' => 'Etiopía', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'FO', 'nombre' => 'Islas Feroe', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PH', 'nombre' => 'Filipinas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'FI', 'nombre' => 'Finlandia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'FJ', 'nombre' => 'Fiyi', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'FR', 'nombre' => 'Francia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GA', 'nombre' => 'Gabón', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GM', 'nombre' => 'Gambia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GE', 'nombre' => 'Georgia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GS', 'nombre' => 'Islas Georgias del Sur y Sandwich del Sur', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GH', 'nombre' => 'Ghana', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GI', 'nombre' => 'Gibraltar', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GD', 'nombre' => 'Granada', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GR', 'nombre' => 'Grecia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GL', 'nombre' => 'Groenlandia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GP', 'nombre' => 'Guadalupe', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GU', 'nombre' => 'Guam', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GT', 'nombre' => 'Guatemala', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GF', 'nombre' => 'Guayana Francesa', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GN', 'nombre' => 'Guinea', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GQ', 'nombre' => 'Guinea Ecuatorial', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GW', 'nombre' => 'Guinea-Bissau', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GY', 'nombre' => 'Guyana', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'HT', 'nombre' => 'Haití', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'HM', 'nombre' => 'Islas Heard y McDonald', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'HN', 'nombre' => 'Honduras', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'HK', 'nombre' => 'Hong Kong', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'HU', 'nombre' => 'Hungría', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IN', 'nombre' => 'India', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ID', 'nombre' => 'Indonesia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IR', 'nombre' => 'Irán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IQ', 'nombre' => 'Iraq', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IE', 'nombre' => 'Irlanda', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IS', 'nombre' => 'Islandia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IL', 'nombre' => 'Israel', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IT', 'nombre' => 'Italia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'JM', 'nombre' => 'Jamaica', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'JP', 'nombre' => 'Japón', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'JO', 'nombre' => 'Jordania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KZ', 'nombre' => 'Kazajstán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KE', 'nombre' => 'Kenia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KG', 'nombre' => 'Kirguistán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KI', 'nombre' => 'Kiribati', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KW', 'nombre' => 'Kuwait', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LA', 'nombre' => 'Laos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LS', 'nombre' => 'Lesotho', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LV', 'nombre' => 'Letonia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LB', 'nombre' => 'Líbano', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LR', 'nombre' => 'Liberia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LY', 'nombre' => 'Libia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LI', 'nombre' => 'Liechtenstein', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LT', 'nombre' => 'Lituania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LU', 'nombre' => 'Luxemburgo', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MO', 'nombre' => 'Macao', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MK', 'nombre' => 'ARY Macedonia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MG', 'nombre' => 'Madagascar', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MY', 'nombre' => 'Malasia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MW', 'nombre' => 'Malawi', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MV', 'nombre' => 'Maldivas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ML', 'nombre' => 'Malí', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MT', 'nombre' => 'Malta', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'FK', 'nombre' => 'Islas Malvinas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MP', 'nombre' => 'Islas Marianas del Norte', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MA', 'nombre' => 'Marruecos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MH', 'nombre' => 'Islas Marshall', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MQ', 'nombre' => 'Martinica', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MU', 'nombre' => 'Mauricio', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MR', 'nombre' => 'Mauritania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'YT', 'nombre' => 'Mayotte', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MX', 'nombre' => 'México', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'FM', 'nombre' => 'Micronesia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MD', 'nombre' => 'Moldavia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MC', 'nombre' => 'Mónaco', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MN', 'nombre' => 'Mongolia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MS', 'nombre' => 'Montserrat', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MZ', 'nombre' => 'Mozambique', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'MM', 'nombre' => 'Myanmar', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NA', 'nombre' => 'Namibia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NR', 'nombre' => 'Nauru', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NP', 'nombre' => 'Nepal', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NI', 'nombre' => 'Nicaragua', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NE', 'nombre' => 'Níger', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NG', 'nombre' => 'Nigeria', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NU', 'nombre' => 'Niue', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NF', 'nombre' => 'Isla Norfolk', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NO', 'nombre' => 'Noruega', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NC', 'nombre' => 'Nueva Caledonia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NZ', 'nombre' => 'Nueva Zelanda', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'OM', 'nombre' => 'Omán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'NL', 'nombre' => 'Países Bajos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PK', 'nombre' => 'Pakistán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PW', 'nombre' => 'Palau', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PS', 'nombre' => 'Palestina', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PA', 'nombre' => 'Panamá', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PG', 'nombre' => 'Papúa Nueva Guinea', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PY', 'nombre' => 'Paraguay', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PE', 'nombre' => 'Perú', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PN', 'nombre' => 'Islas Pitcairn', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PF', 'nombre' => 'Polinesia Francesa', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PL', 'nombre' => 'Polonia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PT', 'nombre' => 'Portugal', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PR', 'nombre' => 'Puerto Rico', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'QA', 'nombre' => 'Qatar', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'GB', 'nombre' => 'Reino Unido', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'RE', 'nombre' => 'Reunión', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'RW', 'nombre' => 'Ruanda', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'RO', 'nombre' => 'Rumania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'RU', 'nombre' => 'Rusia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'EH', 'nombre' => 'Sahara Occidental', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SB', 'nombre' => 'Islas Salomón', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'WS', 'nombre' => 'Samoa', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'AS', 'nombre' => 'Samoa Americana', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'KN', 'nombre' => 'San Cristóbal y Nevis', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SM', 'nombre' => 'San Marino', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'PM', 'nombre' => 'San Pedro y Miquelón', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VC', 'nombre' => 'San Vicente y las Granadinas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SH', 'nombre' => 'Santa Helena', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LC', 'nombre' => 'Santa Lucía', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ST', 'nombre' => 'Santo Tomé y Príncipe', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SN', 'nombre' => 'Senegal', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CS', 'nombre' => 'Serbia y Montenegro', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SC', 'nombre' => 'Seychelles', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SL', 'nombre' => 'Sierra Leona', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SG', 'nombre' => 'Singapur', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SY', 'nombre' => 'Siria', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SO', 'nombre' => 'Somalia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'LK', 'nombre' => 'Sri Lanka', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SZ', 'nombre' => 'Suazilandia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ZA', 'nombre' => 'Sudáfrica', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SD', 'nombre' => 'Sudán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SE', 'nombre' => 'Suecia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'CH', 'nombre' => 'Suiza', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SR', 'nombre' => 'Surinam', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'SJ', 'nombre' => 'Svalbard y Jan Mayen', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TH', 'nombre' => 'Tailandia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TW', 'nombre' => 'Taiwán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TZ', 'nombre' => 'Tanzania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TJ', 'nombre' => 'Tayikistán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'IO', 'nombre' => 'Territorio Británico del Océano Índico', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TF', 'nombre' => 'Territorios Australes Franceses', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TL', 'nombre' => 'Timor Oriental', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TG', 'nombre' => 'Togo', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TK', 'nombre' => 'Tokelau', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TO', 'nombre' => 'Tonga', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TT', 'nombre' => 'Trinidad y Tobago', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TN', 'nombre' => 'Túnez', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TC', 'nombre' => 'Islas Turcas y Caicos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TM', 'nombre' => 'Turkmenistán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TR', 'nombre' => 'Turquía', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'TV', 'nombre' => 'Tuvalu', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'UA', 'nombre' => 'Ucrania', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'UG', 'nombre' => 'Uganda', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'UY', 'nombre' => 'Uruguay', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'UZ', 'nombre' => 'Uzbekistán', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VU', 'nombre' => 'Vanuatu', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VE', 'nombre' => 'Venezuela', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VN', 'nombre' => 'Vietnam', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VG', 'nombre' => 'Islas Vírgenes Británicas', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'VI', 'nombre' => 'Islas Vírgenes de los Estados Unidos', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'WF', 'nombre' => 'Wallis y Futuna', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'YE', 'nombre' => 'Yemen', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'DJ', 'nombre' => 'Yibuti', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ZM', 'nombre' => 'Zambia', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['iso' => 'ZW', 'nombre' => 'Zimbabue', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
        ]);
    }
}
